### ISSUE TITLE
Do not unquote string in expressions

### ISSUE THREAD

**Issue by sergeche** [sergeche/livestyle#22]
When expression is evaluated, explicit strings are unquoted automatically:

``` less
.example{
  @s: "/";
  background-image: "@{s}a.png";
}
```

is transformed into

``` css
.example{
  background-image: /a.png;
}
```
