### ISSUE TITLE
Concat array with space

### ISSUE THREAD

**Issue by sergeche** [sergeche/livestyle#23]
In LESS (at least), arrays in expression must be concatenated with space, not comma:

``` less
.mixin-arguments (@width: 0px, ...) {
    border: @arguments;
    width: @width;
}

.arguments {
    .mixin-arguments(1px, solid, black);
}
```

...should produce 

``` css
.arguments {
  border: 1px solid #000000;
  width: 1px;
}
```
