### ISSUE TITLE
Implement `default()`

### ISSUE THREAD

**Issue by sergeche** [sergeche/livestyle#24]
Available only inside guard conditions and returns `true` only if no other mixin matches, `false` otherwise.

``` css
.mixin(1)                   {x: 11}
.mixin(2)                   {y: 22}
.mixin(@x) when (default()) {z: @x}

div {
  .mixin(3);
}

div.special {
  .mixin(1);
}
```
