### ISSUE TITLE
Mixin locking

### ISSUE THREAD

**Issue by sergeche** [sergeche/livestyle#25]
The following code:

``` css
.lock-mixin(@a) {
 .inner-locked-mixin(@x: @a) when (@a = 1) {
    a: @a;
    x: @x;
  }
}
.call-lock-mixin {
  .lock-mixin(1);
  .call-inner-lock-mixin {
    .inner-locked-mixin();
  }
}
```

...should generate

``` css
.call-lock-mixin .call-inner-lock-mixin {
  a: 1;
  x: 1;
}
```
